# Generated by Django 4.2.16 on 2026-05-03 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='admin_role',
            field=models.CharField(default='Secure Clearance', max_length=100),
        ),
    ]
