# Generated by Django 4.2.16 on 2026-05-03 13:43

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_party_candidate_party'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.candidate_photo_path),
        ),
    ]
